## Switches
set_property PACKAGE_PIN V17 [get_ports {a[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property PACKAGE_PIN V16 [get_ports {a[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property PACKAGE_PIN W16 [get_ports {a[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
set_property PACKAGE_PIN W17 [get_ports {a[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
set_property PACKAGE_PIN W15 [get_ports {b[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property PACKAGE_PIN V15 [get_ports {b[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property PACKAGE_PIN W14 [get_ports {b[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property PACKAGE_PIN W13 [get_ports {b[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]

set_property PACKAGE_PIN U1 [get_ports {opcode[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {opcode[0]}]
set_property PACKAGE_PIN T1 [get_ports {opcode[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {opcode[1]}]
set_property PACKAGE_PIN R2 [get_ports {opcode[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {opcode[2]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {result[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property PACKAGE_PIN E19 [get_ports {result[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property PACKAGE_PIN U19 [get_ports {result[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property PACKAGE_PIN V19 [get_ports {result[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]

set_property PACKAGE_PIN V13 [get_ports carry]					
	set_property IOSTANDARD LVCMOS33 [get_ports carry]
set_property PACKAGE_PIN V3 [get_ports zero_flag]					
	set_property IOSTANDARD LVCMOS33 [get_ports zero_flag]
set_property PACKAGE_PIN W3 [get_ports neg_flag]					
	set_property IOSTANDARD LVCMOS33 [get_ports neg_flag]
